ARG ECR_PYTHON_SLIMBUSTER

FROM ${ECR_PYTHON_SLIMBUSTER}

RUN echo "DEBUG: ECR_PYTHON_SLIMBUSTER=${ECR_PYTHON_SLIMBUSTER}"

WORKDIR /backend-flask 

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE ${PORT}

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=4567", "--no-debug", "--no-debugger", "--no-reload"]
