#! /usr/bin/bash

cd backend-flask

export BACKEND_ECR_SLIMBUSTER="${ECR_PYTHON_SLIMBUSTER}"

echo "DEBUG: BACKEND_ECR_SLIMBUSTER='$BACKEND_ECR_SLIMBUSTER'"   

docker build --build-arg ECR_PYTHON_SLIMBUSTER="${BACKEND_ECR_SLIMBUSTER}" -f Dockerfile.prod -t backend-flask-prod .

docker tag backend-flask-prod:latest $ECR_BACKEND_FLASK_URL:latest

docker push $ECR_BACKEND_FLASK_URL:latest

cd ..

aws ecs register-task-definition --cli-input-json "file://aws/task-definitions/backend-flask.json"

